root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./.build/api"
  cmd = "go build -o ./.build/api ./cmd/api"
  delay = 1000
  exclude_dir = ["tmp", ".git", ".build"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["cmd", "internal", "pkg"]
  include_ext = ["go", "tpl"]
  include_file = []
  kill_delay = "0s"
  log = "./.build/build-errors.log"
  poll = true
  poll_interval = 500
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false
  watcher = true

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true