version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - gocyclo
    - unused
    - dogsled
    - unparam
    - testifylint
    - testpackage
    - spancheck
    - sloglint
    - recvcheck
    - reassign
    - prealloc
    - perfsprint
    - noctx
    - nilnil
    - mnd
    - misspell
    - mirror
    - makezero
    - maintidx
    - loggercheck
    - importas
    - iface
    - gosmopolitan
    - gosec
    - gocritic
    - goconst
    - gocognit
    - gochecksumtype
    - gochecknoglobals
    - funlen
    - funcorder

linters-settings:
  gocyclo:
    min-complexity: 15

  revive:
    severity: warning
    confidence: 0.8

issues:
  exclude-use-default: false